# Generated by Django 5.2.1 on 2026-06-01 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_rename_last_udpted_at_document_last_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='url_pdf',
            field=models.URLField(blank=True, null=True),
        ),
    ]
