# Generated by Django 5.2.1 on 2026-06-02 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_url_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='open_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
