# Generated by Django 5.2.1 on 2026-05-31 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_rename_last_udpted_at_document_last_updated_at_and_more'),
        ('signers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signer',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='signer',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='signers', to='documents.document'),
        ),
    ]
