# Generated by Django 5.2.1 on 2026-06-01 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signers', '0002_signer_deleted_at_alter_signer_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='signer',
            name='sign_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
